spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: commandes-id
          uri: lb://commandes
          predicates:
            - Path=/commandes/**
        - id: clients-id
          uri: lb://clients
          predicates:
            - Path=/clients/**
        - id: restaurants-id
          uri: lb://restaurants
          predicates:
            - Path=/restaurants/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka